# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Rebecca on Rails'
tagline:          'Developer in Progress'
description:      'Currently a student at Ronin by Makers Academy.'
url:              http://rpiper93.github.io
baseurl:          /

# author:
  # name:           'Mark Otto'
  # url:            https://twitter.com/mdo

paginate:         5

github:
  repo:           https://github.com/RPiper93
